// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbskxkneoicrzblwmpfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRic2t4a25lb2ljcnpibHdtcGZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczMzc2MzMsImV4cCI6MjA1MjkxMzYzM30.1eeDvbCZrH3XkbRaw3U9vZTe3hYaWbCsJGLipJa3IA0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);